#!/usr/bin/env python3
"""Build figma-plugin/ui.html from the shared engine sources + panel sources.

The plugin panel runs the SAME engine as the web tool — src/*.js are bundled
(module syntax stripped) into one inline script, together with an ENGINE_SRC
string (the exportable runtime) used by the panel's Copy JS / Copy HTML.

Run after changing src/*.js or figma-plugin/ui-src/*:  python3 build_plugin.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).parent
SRC = ROOT / 'src'
UI = ROOT / 'figma-plugin' / 'ui-src'
OUT = ROOT / 'figma-plugin' / 'ui.html'

# Same transform as stripModuleSyntax in src/presets.js
def strip_modules(text):
    text = re.sub(r'^\s*import[^\n]*\n', '', text, flags=re.M)
    text = re.sub(r'^(\s*)export\s+(?=(async|const|function|class|let|var)\b)', r'\1', text, flags=re.M)
    text = re.sub(r'^\s*export\s+\{[^}]*\};?\s*$', '', text, flags=re.M)
    return text

def read(path):
    return path.read_text()

# Modules the panel runs directly (order matters: dependencies first).
panel_bundle = '\n'.join(strip_modules(read(SRC / name)) for name in [
    'shader.glsl.js', 'shader-mesh.js', 'color.js', 'gradient.js',
    'figma-import.js', 'presets.js',
])

# The exportable runtime embedded as a string for Copy JS / Copy HTML
# (mirrors buildStandaloneJS's inputs in src/presets.js).
engine_src = '\n'.join(strip_modules(read(SRC / name)) for name in [
    'shader.glsl.js', 'shader-mesh.js', 'gradient.js',
])

script = (
    panel_bundle
    + '\nconst ENGINE_SRC = ' + json.dumps(engine_src) + ';\n'
    + read(UI / 'panel.js')
)
# The HTML parser must never see a raw </script> inside the inline block.
script = script.replace('</script', '<\\/script')

html = (
    '<meta charset="utf-8">\n'
    '<!-- GENERATED by build_plugin.py — edit figma-plugin/ui-src/* and src/*, then rebuild -->\n'
    '<style>\n' + read(UI / 'panel.css') + '</style>\n'
    + read(UI / 'template.html')
    + '<script>\n' + script + '\n</script>\n'
)
OUT.write_text(html)
print(f'Wrote {OUT} ({len(html) // 1024} KB)')
