// Mesh Gradient — plugin main thread. The UI panel (ui.html, generated by
// build_plugin.py) is a full editor running the shared WebGL engine; this side
// does all Figma document work: read/apply fills, image fills, variables, and
// preset persistence.

figma.showUI(__html__, { width: 380, height: 610, themeColors: true });

const PRESET_KEY = 'mesh-gradient.presets';
const SHADER_MAP_KEY = 'mesh-gradient.shader-map';
const VAR_LINK_KEY = 'mesh-gradient.linked-collection';

// Pick a collection's Light/Dark modes by name. When a collection has no
// light/dark-named modes (e.g. a brand-theme or single-mode collection), both
// fall back to its DEFAULT mode — never an arbitrary other mode.
function lightDarkModes(col) {
  const def = col.modes.find((m) => m.modeId === col.defaultModeId) || col.modes[0];
  const light = col.modes.find((m) => /light/i.test(m.name)) || def;
  const dark = col.modes.find((m) => /dark/i.test(m.name)) || def;
  return { light, dark };
}

// Normalize the stored link: legacy plain string -> { id, overrides }.
async function getVarLink() {
  const raw = await storageGet(VAR_LINK_KEY);
  if (!raw) return null;
  if (typeof raw === 'string') return { id: raw, overrides: {} };
  return { id: raw.id, overrides: raw.overrides || {} };
}

// Resolve a variable's COLOR value for a mode, following aliases across
// collections. Mode choice per hop: a light/dark-named mode wins; else the
// user's theme override for that collection; else the collection's default.
async function resolveColor(variable, modeKind, overrides, depth) {
  if (!variable || (depth || 0) > 8) return null;
  const col = await figma.variables.getVariableCollectionByIdAsync(variable.variableCollectionId);
  if (!col) return null;
  let mode = lightDarkModes(col)[modeKind];
  const named = /light/i.test(mode.name) || /dark/i.test(mode.name);
  if (!named && overrides && overrides[col.id]) {
    mode = col.modes.find((m) => m.modeId === overrides[col.id]) || mode;
  }
  const value = variable.valuesByMode[mode.modeId];
  if (value && value.type === 'VARIABLE_ALIAS') {
    const next = await figma.variables.getVariableByIdAsync(value.id);
    return resolveColor(next, modeKind, overrides, (depth || 0) + 1);
  }
  if (value && typeof value.r === 'number') return { r: value.r, g: value.g, b: value.b };
  return null;
}

// Walk the alias graph from a set of variables and collect every collection
// that has multiple modes with none named light/dark — those are theme axes
// the user should get a picker for.
async function findThemeHops(startVars) {
  const hops = {};
  const visited = {};
  async function walk(variable, depth) {
    if (!variable || depth > 6 || visited[variable.id]) return;
    visited[variable.id] = true;
    const col = await figma.variables.getVariableCollectionByIdAsync(variable.variableCollectionId);
    if (!col) return;
    const hasNamed = col.modes.some((m) => /light|dark/i.test(m.name));
    if (col.modes.length > 1 && !hasNamed && !hops[col.id]) {
      hops[col.id] = {
        id: col.id,
        name: col.name,
        defaultModeId: col.defaultModeId,
        modes: col.modes.map((m) => ({ modeId: m.modeId, name: m.name })),
      };
    }
    for (const modeId in variable.valuesByMode) {
      const value = variable.valuesByMode[modeId];
      if (value && value.type === 'VARIABLE_ALIAS') {
        await walk(await figma.variables.getVariableByIdAsync(value.id), depth + 1);
      }
    }
  }
  for (const v of startVars) await walk(v, 0);
  return Object.keys(hops).map((k) => hops[k]);
}

// Load the linked collection's color variables (importing them for library
// links), shared by pull and analysis.
async function linkedColorVars(link, limit) {
  if (link.id.indexOf('lib:') === 0) {
    const libVars = await figma.teamLibrary.getVariablesInLibraryCollectionAsync(link.id.slice(4));
    const colorLibVars = libVars.filter((v) => v.resolvedType === 'COLOR').slice(0, limit);
    const out = [];
    for (const lv of colorLibVars) out.push(await figma.variables.importVariableByKeyAsync(lv.key));
    return out;
  }
  const id = link.id.indexOf('local:') === 0 ? link.id.slice(6) : link.id;
  const col = await figma.variables.getVariableCollectionByIdAsync(id);
  if (!col) return null;
  return (await colorVariablesOf(col)).slice(0, limit);
}

async function sendThemeHops(link) {
  const vars = await linkedColorVars(link, 6);
  if (!vars) return;
  const hops = await findThemeHops(vars);
  reply({ type: 'collection-modes', hops, overrides: link.overrides });
}

// A collection's COLOR variables, in collection order.
async function colorVariablesOf(col) {
  const vars = await Promise.all(col.variableIds.map((id) => figma.variables.getVariableByIdAsync(id)));
  return vars.filter((v) => v && v.resolvedType === 'COLOR');
}

function reply(msg) { figma.ui.postMessage(msg); }
function status(ok, error) { reply({ type: 'status', ok, error }); }
// Figma plugin APIs sometimes throw plain strings — String(e) keeps the real text.
function errText(e) { return (e && e.message) ? e.message : String(e); }

// clientStorage requires a plugin id in the manifest; fail soft so features
// still work within the session even if storage is unavailable.
async function storageGet(key) {
  try { return await figma.clientStorage.getAsync(key); } catch (e) { return null; }
}
async function storageSet(key, value) {
  try { await figma.clientStorage.setAsync(key, value); } catch (e) { /* non-fatal */ }
}

function fillableSelection() {
  return figma.currentPage.selection.filter((n) => 'fills' in n);
}

function hexToRgba(hex) {
  const n = parseInt(hex.replace('#', ''), 16);
  return { r: ((n >> 16) & 255) / 255, g: ((n >> 8) & 255) / 255, b: (n & 255) / 255, a: 1 };
}

figma.ui.onmessage = async (msg) => {
  // ---- presets (clientStorage) ---------------------------------------------
  if (msg.type === 'get-presets') {
    const presets = (await storageGet(PRESET_KEY)) || {};
    reply({ type: 'presets', presets });

  } else if (msg.type === 'save-presets') {
    await storageSet(PRESET_KEY, msg.presets || {});

  // ---- variable collection link --------------------------------------------
  // Collections can be LOCAL (defined in this file) or LIBRARY (published from
  // another file — how token setups usually arrive). Library variables are
  // invisible to the local API; they're enumerated via teamLibrary and
  // imported on pull. Linked ids are prefixed 'local:' / 'lib:'.
  } else if (msg.type === 'get-collections') {
    const list = [];
    let step = 'local variables';
    try {
      const collections = await figma.variables.getLocalVariableCollectionsAsync();
      for (const col of collections) {
        const colorVars = await colorVariablesOf(col);
        if (colorVars.length) list.push({ id: 'local:' + col.id, name: col.name, colorCount: colorVars.length });
      }
      step = 'library variables';
      try {
        const libCols = await figma.teamLibrary.getAvailableLibraryVariableCollectionsAsync();
        for (const lc of libCols) {
          const libVars = await figma.teamLibrary.getVariablesInLibraryCollectionAsync(lc.key);
          const colorCount = libVars.filter((v) => v.resolvedType === 'COLOR').length;
          if (colorCount) {
            list.push({ id: 'lib:' + lc.key, name: lc.name + ' — ' + lc.libraryName, colorCount });
          }
        }
      } catch (e) { /* team library unavailable (drafts / no permission) — locals still listed */ }
      step = 'link restore';
      const link = await getVarLink();
      reply({ type: 'collections', list, linkedId: link ? link.id : null });
      if (!list.length) status(null, 'No color-variable collections found (local or library) in this file.');
      if (link) {
        try { await sendThemeHops(link); } catch (e) { /* pickers are optional */ }
      }
    } catch (e) {
      // still deliver whatever was collected so the dropdown isn't dead
      reply({ type: 'collections', list, linkedId: null });
      status(null, 'Listing variables failed at ' + step + ': ' + errText(e));
    }

  } else if (msg.type === 'link-collection') {
    if (!msg.collectionId) {
      await storageSet(VAR_LINK_KEY, null);
    } else {
      const link = { id: msg.collectionId, overrides: {} };
      await storageSet(VAR_LINK_KEY, link);
      try { await sendThemeHops(link); } catch (e) { /* pickers are optional */ }
    }

  } else if (msg.type === 'set-mode-override') {
    const link = await getVarLink();
    if (link) {
      link.overrides[msg.collectionId] = msg.modeId;
      await storageSet(VAR_LINK_KEY, link);
    }

  } else if (msg.type === 'pull-variables') {
    try {
      const link = await getVarLink();
      if (!link) return status(null, 'Link a collection first.');
      const colorVars = await linkedColorVars(link, 16);
      if (!colorVars) return status(null, 'Linked collection not found — pick one again.');
      if (!colorVars.length) return status(null, 'No color variables in that collection.');
      const palette = [];
      for (const v of colorVars) {
        palette.push({
          name: v.name,
          light: await resolveColor(v, 'light', link.overrides),
          dark: await resolveColor(v, 'dark', link.overrides),
        });
      }
      reply({ type: 'variables-pulled', palette });
    } catch (e) {
      status(null, 'Pull failed: ' + errText(e));
    }

  // ---- custom shader targeting ---------------------------------------------
  } else if (msg.type === 'get-shader-map') {
    const map = (await storageGet(SHADER_MAP_KEY)) || null;
    reply({ type: 'shader-map', map });

  } else if (msg.type === 'save-shader-map') {
    await storageSet(SHADER_MAP_KEY, msg.map || null);

  } else if (msg.type === 'capture-shader') {
    const node = figma.currentPage.selection.find(
      (n) => 'fills' in n && Array.isArray(n.fills) && n.fills.some((f) => f.type === 'SHADER')
    );
    if (!node) return status(null, 'Select a layer filled with your custom shader first.');
    const shader = node.fills.find((f) => f.type === 'SHADER');
    reply({ type: 'shader-captured', id: shader.id, properties: shader.properties });

  // ---- import the selected mesh (with a PNG reference for refinement) ------
  } else if (msg.type === 'import-selection') {
    const node = figma.currentPage.selection.find(
      (n) => 'fills' in n && Array.isArray(n.fills) && n.fills.some((f) => f.type === 'SHADER')
    );
    if (!node) return status(null, 'Select a layer with a mesh gradient fill.');
    const shader = node.fills.find((f) => f.type === 'SHADER');
    let refBytes = null;
    try {
      refBytes = await node.exportAsync({
        format: 'PNG',
        constraint: { type: 'WIDTH', value: 320 },
      });
    } catch (e) { /* refinement is optional */ }
    reply({
      type: 'selection-mesh',
      properties: shader.properties,
      width: node.width,
      height: node.height,
      refBytes,
    });

  // ---- apply as native mesh shader fill ------------------------------------
  } else if (msg.type === 'apply-shader') {
    const targets = fillableSelection();
    if (!targets.length) return status(null, 'Select a frame or shape first.');
    try {
      targets.forEach((n) => { n.fills = [msg.paint]; });
      figma.notify('Mesh gradient applied to ' + targets.length + ' layer(s)');
      status('Applied mesh fill to ' + targets.length + ' layer(s).');
    } catch (e) {
      status(null, 'Apply failed: ' + errText(e));
    }

  // ---- apply the paused frame as an image fill ------------------------------
  } else if (msg.type === 'image-size-request') {
    const target = fillableSelection()[0];
    if (!target) return status(null, 'Select a frame or shape first.');
    reply({ type: 'image-size', width: Math.round(target.width), height: Math.round(target.height) });

  } else if (msg.type === 'apply-image') {
    const targets = fillableSelection();
    if (!targets.length) return status(null, 'Selection changed — select the target again.');
    try {
      const image = figma.createImage(new Uint8Array(msg.bytes));
      targets.forEach((n) => {
        n.fills = [{ type: 'IMAGE', imageHash: image.hash, scaleMode: 'FILL' }];
      });
      figma.notify('Frame applied as image fill');
      status('Paused frame applied as image fill.');
    } catch (e) {
      status(null, 'Image fill failed: ' + errText(e));
    }

  // ---- create/update Light/Dark variables ----------------------------------
  // Writes to the LINKED collection when one is set (index-mapped onto its
  // color variables, creating extras if it has fewer than the palette).
  // With no link, creates/updates a local "Mesh Gradient" collection.
  } else if (msg.type === 'make-variables') {
    try {
      let col = null;
      const link = await getVarLink();
      if (link && link.id.indexOf('lib:') === 0) {
        return status(null, 'The linked collection is a published library — edit its variables in the library file itself. (Pull works here; Push can’t write across files.)');
      }
      if (link) {
        const id = link.id.indexOf('local:') === 0 ? link.id.slice(6) : link.id;
        col = await figma.variables.getVariableCollectionByIdAsync(id);
      }
      if (!col) {
        const collections = await figma.variables.getLocalVariableCollectionsAsync();
        col = collections.find((c) => c.name === 'Mesh Gradient');
        if (!col) {
          col = figma.variables.createVariableCollection('Mesh Gradient');
          col.renameMode(col.modes[0].modeId, 'Light');
          col.addMode('Dark');
        }
      }
      const modes = lightDarkModes(col);
      if (modes.light.modeId === modes.dark.modeId && col.modes.length === 1) {
        try { modes.dark = { modeId: col.addMode('Dark'), name: 'Dark' }; } catch (e) { /* mode limit */ }
      }
      const colorVars = await colorVariablesOf(col);
      for (let i = 0; i < msg.palette.length; i++) {
        const item = msg.palette[i];
        let v = colorVars[i];
        if (!v) {
          v = figma.variables.createVariable(item.name, col, 'COLOR');
          v.scopes = ['FRAME_FILL', 'SHAPE_FILL'];
        }
        v.setValueForMode(modes.light.modeId, hexToRgba(item.light));
        if (modes.dark.modeId !== modes.light.modeId) v.setValueForMode(modes.dark.modeId, hexToRgba(item.dark));
      }
      figma.notify('Variables updated in "' + col.name + '" (' + msg.palette.length + ')');
      status('Pushed ' + msg.palette.length + ' colors × Light/Dark to "' + col.name + '".');
    } catch (e) {
      status(null, 'Variables failed: ' + errText(e));
    }
  }
};
