// Mesh Gradient — plugin main thread. The UI panel (ui.html, generated by
// build_plugin.py) is a full editor running the shared WebGL engine; this side
// does all Figma document work: read/apply fills, image fills, variables, and
// preset persistence.

figma.showUI(__html__, { width: 380, height: 610, themeColors: true });

const PRESET_KEY = 'mesh-gradient.presets';

function reply(msg) { figma.ui.postMessage(msg); }
function status(ok, error) { reply({ type: 'status', ok, error }); }

function fillableSelection() {
  return figma.currentPage.selection.filter((n) => 'fills' in n);
}

function hexToRgba(hex) {
  const n = parseInt(hex.replace('#', ''), 16);
  return { r: ((n >> 16) & 255) / 255, g: ((n >> 8) & 255) / 255, b: (n & 255) / 255, a: 1 };
}

figma.ui.onmessage = async (msg) => {
  // ---- presets (clientStorage) ---------------------------------------------
  if (msg.type === 'get-presets') {
    const presets = (await figma.clientStorage.getAsync(PRESET_KEY)) || {};
    reply({ type: 'presets', presets });

  } else if (msg.type === 'save-presets') {
    await figma.clientStorage.setAsync(PRESET_KEY, msg.presets || {});

  // ---- import the selected mesh (with a PNG reference for refinement) ------
  } else if (msg.type === 'import-selection') {
    const node = figma.currentPage.selection.find(
      (n) => 'fills' in n && Array.isArray(n.fills) && n.fills.some((f) => f.type === 'SHADER')
    );
    if (!node) return status(null, 'Select a layer with a mesh gradient fill.');
    const shader = node.fills.find((f) => f.type === 'SHADER');
    let refBytes = null;
    try {
      refBytes = await node.exportAsync({
        format: 'PNG',
        constraint: { type: 'WIDTH', value: 320 },
      });
    } catch (e) { /* refinement is optional */ }
    reply({
      type: 'selection-mesh',
      properties: shader.properties,
      width: node.width,
      height: node.height,
      refBytes,
    });

  // ---- apply as native mesh shader fill ------------------------------------
  } else if (msg.type === 'apply-shader') {
    const targets = fillableSelection();
    if (!targets.length) return status(null, 'Select a frame or shape first.');
    try {
      targets.forEach((n) => { n.fills = [msg.paint]; });
      figma.notify('Mesh gradient applied to ' + targets.length + ' layer(s)');
      status('Applied mesh fill to ' + targets.length + ' layer(s).');
    } catch (e) {
      status(null, 'Apply failed: ' + e.message);
    }

  // ---- apply the paused frame as an image fill ------------------------------
  } else if (msg.type === 'image-size-request') {
    const target = fillableSelection()[0];
    if (!target) return status(null, 'Select a frame or shape first.');
    reply({ type: 'image-size', width: Math.round(target.width), height: Math.round(target.height) });

  } else if (msg.type === 'apply-image') {
    const targets = fillableSelection();
    if (!targets.length) return status(null, 'Selection changed — select the target again.');
    try {
      const image = figma.createImage(new Uint8Array(msg.bytes));
      targets.forEach((n) => {
        n.fills = [{ type: 'IMAGE', imageHash: image.hash, scaleMode: 'FILL' }];
      });
      figma.notify('Frame applied as image fill');
      status('Paused frame applied as image fill.');
    } catch (e) {
      status(null, 'Image fill failed: ' + e.message);
    }

  // ---- create/update the Light/Dark variable collection ---------------------
  } else if (msg.type === 'make-variables') {
    try {
      const collections = await figma.variables.getLocalVariableCollectionsAsync();
      let col = collections.find((c) => c.name === 'Mesh Gradient');
      if (!col) {
        col = figma.variables.createVariableCollection('Mesh Gradient');
        col.renameMode(col.modes[0].modeId, 'Light');
        col.addMode('Dark');
      }
      const lightId = col.modes[0].modeId;
      const darkId = (col.modes[1] || col.modes[0]).modeId;
      const existing = {};
      for (const id of col.variableIds) {
        const v = await figma.variables.getVariableByIdAsync(id);
        if (v) existing[v.name] = v;
      }
      for (const item of msg.palette) {
        const v = existing[item.name] || figma.variables.createVariable(item.name, col, 'COLOR');
        v.scopes = ['FRAME_FILL', 'SHAPE_FILL'];
        v.setValueForMode(lightId, hexToRgba(item.light));
        v.setValueForMode(darkId, hexToRgba(item.dark));
      }
      figma.notify('Mesh Gradient variables updated (' + msg.palette.length + ')');
      status('Variables ready: ' + msg.palette.length + ' colors × Light/Dark.');
    } catch (e) {
      status(null, 'Variables failed: ' + e.message);
    }
  }
};
